### ISSUE TITLE
What license is this code available under?

### ISSUE THREAD

**Issue by b4hand** [malbrain/HatTrie#1]
There's no license file in the repository, and no mention of a license in the readme.md or in the code itself.

**Comment by malbrain** [comment]
The code is released to the public domain.  All I ask is that you report any bugs or other problems.

Karl 

On Wednesday, July 2, 2014 12:13 PM, Brandon Forehand notifications@github.com wrote:

There's no license file in the repository, and no mention of a license in the readme.md or in the code itself.
